import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, ScrollText } from 'lucide-react';
import AshokaChakra from '../components/decorative/AshokaChakra';

/**
 * Terms.tsx — public-facing terms of service.
 * Includes AI-output disclaimer, prohibited use, account termination.
 * Bilingual layout, no auth required.
 */

const Section: React.FC<{ title: string; titleHi?: string; children: React.ReactNode }> = ({ title, titleHi, children }) => (
  <section className="space-y-2">
    <h2 className="text-lg font-semibold text-kora-100">
      {title}
      {titleHi && <span className="block font-devanagari text-sm text-slate-400/70 font-normal mt-0.5">{titleHi}</span>}
    </h2>
    <div className="text-sm text-slate-300/85 leading-relaxed space-y-2">{children}</div>
  </section>
);

const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-[#060B18] text-slate-200">
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="aurora-orb w-[600px] h-[600px] bg-[#0D92F4]/10 top-[-10%] left-[-10%]" />
        <div className="aurora-orb w-[400px] h-[400px] bg-[#F95454]/8 bottom-[-15%] right-[-5%]" style={{ animationDelay: '-7s' }} />
        <div className="absolute inset-0 grain-overlay" />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto px-5 py-10 sm:py-14">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-slate-400 hover:text-[#77CDFF] transition-colors mb-6">
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>

          <header className="mb-10 pb-6 border-b border-white/[0.06]">
            <div className="flex items-center gap-3 mb-3">
              <AshokaChakra size={36} />
              <ScrollText className="w-5 h-5 text-[#77CDFF]" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-display font-bold text-gradient-gold mb-1">Terms of Service</h1>
            <p className="font-devanagari text-lg text-slate-400/70">सेवा की शर्तें</p>
            <p className="text-xs text-slate-500 mt-3">Last updated: 7 May 2026</p>
          </header>

          <div className="space-y-8">
            <Section title="1. Acceptance" titleHi="1. स्वीकृति">
              <p>
                By creating an account on or otherwise using NyayaSetu (न्यायसेतु) you agree
                to these Terms. If you do not agree, please do not use the service.
              </p>
            </Section>

            <Section title="2. About the Service" titleHi="2. सेवा के बारे में">
              <p>
                NyayaSetu is an AI-assisted citizen-governance pilot. It helps citizens
                discover government welfare schemes, file and track grievances, and receive
                official notices. It is operated by the project owner and is currently a
                pilot deployment, not an official government portal.
              </p>
            </Section>

            <Section title="3. AI Output — No Warranty" titleHi="3. एआई आउटपुट — कोई वारंटी नहीं">
              <p className="font-medium text-kora-100">
                Information generated by NyayaSetu's AI systems is informational only. It is
                produced by large language models which may be inaccurate, incomplete or out of date.
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li>AI summaries of schemes are not a substitute for the official scheme document.</li>
                <li>AI-routed grievance categories may be wrong — humans review every grievance.</li>
                <li>Drafted notices must be reviewed by an authorised officer before publication.</li>
                <li>Always verify critical information (eligibility, amounts, deadlines, contact details) with the relevant government department before acting.</li>
              </ul>
              <p>
                The service is provided <em>"as is"</em> and we expressly disclaim all warranties,
                express or implied, including merchantability, fitness for a particular purpose
                and non-infringement, to the extent permitted by Indian law.
              </p>
            </Section>

            <Section title="4. Account &amp; Eligibility" titleHi="4. खाता और पात्रता">
              <ul className="list-disc pl-5 space-y-1">
                <li>You must be 18 years or older, or use the service with parental consent.</li>
                <li>You are responsible for keeping your password confidential.</li>
                <li>One account per person — sharing accounts is prohibited.</li>
                <li>Officer accounts require a valid registration code and verification.</li>
              </ul>
            </Section>

            <Section title="5. Acceptable Use" titleHi="5. स्वीकार्य उपयोग">
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>File false, misleading or vexatious grievances.</li>
                <li>Submit content that is unlawful, threatening, defamatory, obscene or that infringes intellectual property.</li>
                <li>Upload malware, attempt to probe or disrupt the service, or bypass authentication.</li>
                <li>Use automated scripts, bots or scrapers without written permission.</li>
                <li>Impersonate another person or government officer.</li>
                <li>Use the service to attempt to extract personal data of other users.</li>
              </ul>
            </Section>

            <Section title="6. User Content" titleHi="6. उपयोगकर्ता सामग्री">
              <p>
                You retain ownership of grievances, attachments and other content you submit.
                By submitting, you grant NyayaSetu a non-exclusive licence to host, process and
                share that content with the relevant government department for resolution.
              </p>
            </Section>

            <Section title="7. Suspension &amp; Termination" titleHi="7. निलंबन और समाप्ति">
              <p>
                We may suspend or terminate accounts that violate these Terms, breach applicable
                law, or engage in abusive behaviour towards officers or other citizens.
                Termination does not relieve you of obligations accrued before termination.
                You may close your account at any time from the Settings page.
              </p>
            </Section>

            <Section title="8. Limitation of Liability" titleHi="8. दायित्व की सीमा">
              <p>
                To the maximum extent permitted by Indian law, NyayaSetu and its operators are
                not liable for indirect, incidental, special, consequential or punitive damages
                arising from your use of the service, including damages from reliance on AI-generated
                output. Our aggregate liability for direct damages shall not exceed INR 1,000.
              </p>
            </Section>

            <Section title="9. Governing Law" titleHi="9. शासी कानून">
              <p>
                These Terms are governed by the laws of India. Disputes shall be subject to the
                exclusive jurisdiction of the courts located in the project owner's place of
                operation, without prejudice to the consumer-protection rights guaranteed to you
                by law.
              </p>
            </Section>

            <Section title="10. Changes" titleHi="10. परिवर्तन">
              <p>
                We may update these Terms. Material changes will be communicated via in-app
                notification at least seven (7) days before they take effect.
              </p>
            </Section>

            <Section title="11. Contact" titleHi="11. संपर्क">
              <p>
                For questions about these Terms, write to{' '}
                <a className="text-[#77CDFF] hover:underline" href="mailto:legal@nyayasetu.in">legal@nyayasetu.in</a>.
              </p>
            </Section>
          </div>

          <footer className="mt-12 pt-6 border-t border-white/[0.06] flex flex-wrap gap-4 text-xs text-slate-500">
            <Link to="/privacy" className="hover:text-[#77CDFF] transition-colors">Privacy Policy</Link>
            <Link to="/login" className="hover:text-[#77CDFF] transition-colors">Login</Link>
            <Link to="/public/schemes" className="hover:text-[#77CDFF] transition-colors">Browse Schemes</Link>
            <span className="ml-auto">NyayaSetu &middot; पायलट परिनियोजन</span>
          </footer>
        </motion.div>
      </div>
    </div>
  );
};

export default Terms;
